### PR TITLE
feat: role to read from log archive bucket

### LINKED ISSUE #1: Create role for CCCS to assume (Retrieval from global bucket)

### PR DESCRIPTION
**Pull request by patheard**
# Summary 
This will be assumed by the CBS agent to read objects that
are replicated to the log archive bucket.

# Related
* Closes #1

### CODE REVIEW

**Review by mohamed-cds — APPROVED** [review]
Nice! Do you mind creating the lastpass that will contain this TF_VAR and sharing it with us ?

🚀 ✅

**Review by mohamed-cds — CHANGES_REQUESTED** [review]
When you rebase can you add the `TF_VAR_cbs_principal_arn` to the TF plan & apply

**Comment by patheard** [comment]
Done and done with the rebase and adding the `TF_VAR_cbs_principal_arn`

**Review by mohamed-cds — APPROVED** [review]
nice. I didnt know you could encapsulate items in a sensitive block!

🚀 ✅

**Comment by patheard** [comment]
I just learned about them too when I noticed that the sensitive variable value was still being output in the `terraform plan` in the policy JSON block.

**Pull request merged**
